import axios from 'axios';
import { Country, University, CurrencyData, SearchResults } from '@/types';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api/v1';

export const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

api.interceptors.request.use((config) => {
  if (typeof window !== 'undefined') {
    const token = localStorage.getItem('edunex_token');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
  }
  return config;
});

// API Helper Services
export const countryService = {
  getAll: async (): Promise<Country[]> => {
    try {
      const res = await api.get('/countries');
      return res.data.data;
    } catch (err) {
      console.warn('Backend API unavailable, serving client fallback database');
      return getFallbackCountries();
    }
  },
  getBySlug: async (slug: string): Promise<Country> => {
    try {
      const res = await api.get(`/countries/${slug}`);
      return res.data.data;
    } catch (err) {
      console.warn(`Backend API unavailable, serving client fallback dataset for: ${slug}`);
      if (slug === 'austria') return getFallbackAustriaData();
      return getFallbackGermanyData();
    }
  },
};

export const universityService = {
  getFiltered: async (params?: any): Promise<University[]> => {
    try {
      const res = await api.get('/universities', { params });
      return res.data.data;
    } catch (err) {
      const countryData = params?.countrySlug === 'austria' ? getFallbackAustriaData() : getFallbackGermanyData();
      let list = countryData.universities || [];

      if (params?.search) {
        const q = String(params.search).toLowerCase();
        list = list.filter(u => u.name.toLowerCase().includes(q) || u.cityName.toLowerCase().includes(q) || u.description.toLowerCase().includes(q));
      }
      if (params?.city && params.city !== 'All') {
        list = list.filter(u => u.cityName === params.city);
      }
      if (params?.type && params.type !== 'All') {
        list = list.filter(u => u.type === params.type);
      }
      if (params?.degree && params.degree !== 'All') {
        list = list.filter(u => u.degrees.includes(params.degree));
      }
      if (params?.sortBy === 'qsRanking') {
        list = [...list].sort((a, b) => (params.sortOrder === 'desc' ? b.qsRanking - a.qsRanking : a.qsRanking - b.qsRanking));
      }
      return list;
    }
  },
  search: async (countrySlug: string, query: string): Promise<University[]> => {
    try {
      const res = await api.get('/universities', { params: { countrySlug, search: query } });
      return res.data.data;
    } catch (err) {
      const countryData = countrySlug === 'austria' ? getFallbackAustriaData() : getFallbackGermanyData();
      const q = query.toLowerCase();
      return (countryData.universities || []).filter(
        u => u.name.toLowerCase().includes(q) || u.cityName.toLowerCase().includes(q) || u.description.toLowerCase().includes(q)
      );
    }
  },
};

export const currencyService = {
  getRate: async (base = 'EUR', target = 'INR'): Promise<CurrencyData> => {
    try {
      const res = await api.get('/currency/rate', { params: { base, target } });
      return res.data.data;
    } catch (err) {
      return {
        base,
        target,
        rate: 91.25,
        lastUpdated: new Date().toISOString(),
        history: [
          { month: 'Mar', rate: '89.88' },
          { month: 'Apr', rate: '90.34' },
          { month: 'May', rate: '90.75' },
          { month: 'Jun', rate: '91.02' },
          { month: 'Jul', rate: '91.15' },
          { month: 'Aug', rate: '91.25' },
        ],
      };
    }
  },
};

export const searchService = {
  global: async (query: string): Promise<SearchResults> => {
    try {
      const res = await api.get('/search', { params: { q: query } });
      return res.data.data;
    } catch (err) {
      const germany = getFallbackGermanyData();
      const q = query.toLowerCase();
      return {
        universities: (germany.universities || []).filter(u => u.name.toLowerCase().includes(q) || u.cityName.toLowerCase().includes(q)),
        scholarships: (germany.scholarships || []).filter(s => s.title.toLowerCase().includes(q) || s.description.toLowerCase().includes(q)),
        documents: (germany.documents || []).filter(d => d.title.toLowerCase().includes(q)),
        faqs: (germany.faqs || []).filter(f => f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q)),
        resources: (germany.officialResources || []).filter(r => r.title.toLowerCase().includes(q)),
      };
    }
  },
};

// Fallback datasets for zero-downtime client resiliency
function getFallbackCountries(): Country[] {
  return [
    {
      id: 'c-de',
      name: 'Germany',
      slug: 'germany',
      code: 'DE',
      flagEmoji: '🇩🇪',
      avgTuition: '€0 - €3,000 / year',
      avgLivingCost: '€934 - €1,100 / month',
      workHours: '140 full days / year',
      popularIntake: 'Winter (Oct) & Summer (Apr)',
      shortDesc: 'Europe’s leading study destination offering tuition-free public university education, world-class STEM research, and solid post-study career opportunities.',
      isComplete: true,
    },
    {
      id: 'c-at',
      name: 'Austria',
      slug: 'austria',
      code: 'AT',
      flagEmoji: '🇦🇹',
      avgTuition: '€726.72 / semester (non-EU)',
      avgLivingCost: '€950 - €1,300 / month',
      workHours: '20 hours / week',
      popularIntake: 'Winter (Oct) & Summer (Mar)',
      shortDesc: 'A welcoming central-European study hub with affordable public tuition, high quality of life, no APS requirement, and excellent post-study opportunities in the heart of Europe.',
      isComplete: true,
    },
    {
      id: 'c-ca',
      name: 'Canada',
      slug: 'canada',
      code: 'CA',
      flagEmoji: '🇨🇦',
      avgTuition: 'CAD $15,000 - $35,000 / year',
      avgLivingCost: 'CAD $1,200 - $2,000 / month',
      workHours: '20 hours / week',
      popularIntake: 'Fall (Sep) & Winter (Jan)',
      shortDesc: 'Renowned for world-class universities, welcoming policy, and generous Post-Graduation Work Permits.',
      isComplete: false,
    },
    {
      id: 'c-gb',
      name: 'United Kingdom',
      slug: 'united-kingdom',
      code: 'GB',
      flagEmoji: '🇬🇧',
      avgTuition: '£12,000 - £30,000 / year',
      avgLivingCost: '£1,000 - £1,500 / month',
      workHours: '20 hours / week',
      popularIntake: 'Autumn (Sep) & Spring (Jan)',
      shortDesc: 'Home to Oxford, Cambridge, and 1-year intensive Master degrees with Graduate Route visas.',
      isComplete: false,
    },
    {
      id: 'c-au',
      name: 'Australia',
      slug: 'australia',
      code: 'AU',
      flagEmoji: '🇦🇺',
      avgTuition: 'AUD $20,000 - $45,000 / year',
      avgLivingCost: 'AUD $1,400 - $2,200 / month',
      workHours: '48 hours / fortnight',
      popularIntake: 'Feb / Mar & Jul / Aug',
      shortDesc: 'High quality of life, top-ranked universities, breathtaking climate, and extended post-study work rights.',
      isComplete: false,
    },
    {
      id: 'c-ie',
      name: 'Ireland',
      slug: 'ireland',
      code: 'IE',
      flagEmoji: '🇮🇪',
      avgTuition: '€9,800 - €25,000 / year',
      avgLivingCost: '€1,000 - €1,800 / month',
      workHours: '20 hours / week',
      popularIntake: 'Autumn (Sep) & Spring (Jan)',
      shortDesc: 'Silicon Valley of Europe housing global tech headquarters with 2-year post-study work visa for Masters.',
      isComplete: false,
    },
    {
      id: 'c-fr',
      name: 'France',
      slug: 'france',
      code: 'FR',
      flagEmoji: '🇫🇷',
      avgTuition: '€2,770 - €15,000 / year',
      avgLivingCost: '€800 - €1,400 / month',
      workHours: '60% of annual working time',
      popularIntake: 'September & January',
      shortDesc: 'Affordable public university tuition, rich culture, and prestigious Grand Écoles.',
      isComplete: false,
    },
    {
      id: 'c-nl',
      name: 'Netherlands',
      slug: 'netherlands',
      code: 'NL',
      flagEmoji: '🇳🇱',
      avgTuition: '€6,000 - €15,000 / year',
      avgLivingCost: '€900 - €1,500 / month',
      workHours: '16 hours / week',
      popularIntake: 'September & February',
      shortDesc: 'Highest English proficiency in non-English Europe, innovative teaching, and tech startup hubs.',
      isComplete: false,
    },
    {
      id: 'c-nz',
      name: 'New Zealand',
      slug: 'new-zealand',
      code: 'NZ',
      flagEmoji: '🇳🇿',
      avgTuition: 'NZD $22,000 - $35,000 / year',
      avgLivingCost: 'NZD $1,200 - $1,800 / month',
      workHours: '20 hours / week',
      popularIntake: 'February & July',
      shortDesc: 'Safe, serene landscape, practical industry education, and post-study work opportunities.',
      isComplete: false,
    },
    {
      id: 'c-se',
      name: 'Sweden',
      slug: 'sweden',
      code: 'SE',
      flagEmoji: '🇸🇪',
      avgTuition: 'SEK 80,000 - 140,000 / year',
      avgLivingCost: 'SEK 9,500 / month',
      workHours: 'No legal hourly limit for full-time students',
      popularIntake: 'Autumn (August)',
      shortDesc: 'Pioneer in sustainability, equality, and cutting-edge tech innovations.',
      isComplete: false,
    },
    {
      id: 'c-fi',
      name: 'Finland',
      slug: 'finland',
      code: 'FI',
      flagEmoji: '🇫🇮',
      avgTuition: '€6,000 - €12,000 / year',
      avgLivingCost: '€700 - €1,100 / month',
      workHours: '30 hours / week',
      popularIntake: 'Autumn (September)',
      shortDesc: 'Voted happiest country in the world with world-best education system and post-study PR pathway.',
      isComplete: false,
    },
  ];
}

export function getFallbackGermanyData(): Country {
  return {
    id: 'c-de',
    name: 'Germany',
    slug: 'germany',
    code: 'DE',
    flagEmoji: '🇩🇪',
    avgTuition: '€0 - €3,000 / year',
    avgLivingCost: '€934 - €1,100 / month',
    workHours: '140 full days (280 half days) / year',
    popularIntake: 'Winter (Oct) & Summer (Apr)',
    shortDesc: 'Europe’s leading study destination offering tuition-free public university education, world-class STEM research, and solid post-study career opportunities.',
    isComplete: true,
    capital: 'Berlin',
    currency: 'Euro (€)',
    language: 'German (English for many Masters)',
    population: '84.4 Million',
    intStudentsCount: '370,000+',
    semesterContrib: '€150 - €400 / semester (Includes Transit Pass)',
    blockedAccountAmt: '€11,904 / year (€992 / month)',
    minWage: '€13.90 / hour',
    publicUnivCount: 300,
    privateUnivCount: 100,
    topCities: JSON.stringify(['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Aachen', 'Karlsruhe']),
    popularCourses: JSON.stringify(['Computer Science', 'Automotive Engineering', 'Data Science', 'Renewable Energy', 'Mechanical Engineering', 'International Business']),
    climate: 'Temperate (Mild summers, cool winters: -2°C to 25°C)',
    timeDiff: 'UTC+1 (CET) / UTC+2 (CEST)',
    safetyIndex: '75.2 (Very Safe)',
    cities: [
      { id: '1', countryId: 'c-de', name: 'Munich', avgRent: 650, avgFood: 250, avgTransport: 49, avgUtilities: 110, avgInternet: 30, avgEntertainment: 120, totalMonthly: 1209, isPopular: true },
      { id: '2', countryId: 'c-de', name: 'Berlin', avgRent: 550, avgFood: 230, avgTransport: 49, avgUtilities: 95, avgInternet: 28, avgEntertainment: 110, totalMonthly: 1062, isPopular: true },
      { id: '3', countryId: 'c-de', name: 'Aachen', avgRent: 420, avgFood: 200, avgTransport: 0, avgUtilities: 85, avgInternet: 25, avgEntertainment: 80, totalMonthly: 810, isPopular: true },
      { id: '4', countryId: 'c-de', name: 'Karlsruhe', avgRent: 450, avgFood: 210, avgTransport: 0, avgUtilities: 90, avgInternet: 25, avgEntertainment: 85, totalMonthly: 860, isPopular: true },
      { id: '5', countryId: 'c-de', name: 'Frankfurt', avgRent: 600, avgFood: 240, avgTransport: 49, avgUtilities: 105, avgInternet: 30, avgEntertainment: 115, totalMonthly: 1139, isPopular: true },
      { id: '6', countryId: 'c-de', name: 'Hamburg', avgRent: 580, avgFood: 235, avgTransport: 49, avgUtilities: 100, avgInternet: 28, avgEntertainment: 105, totalMonthly: 1097, isPopular: true },
    ],
    universities: [
      {
        id: 'u-1',
        countryId: 'c-de',
        name: 'Technical University of Munich (TUM)',
        slug: 'technical-university-of-munich',
        type: 'Public',
        qsRanking: 28,
        cityName: 'Munich',
        logoUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€150 - €1,500 / semester',
        tuitionFee: '€0 - €6,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.tum.de/en/',
        admissionReqSummary: 'Bachelor degree with top GPA, IELTS 6.5+ or TOEFL 88+, GRE required for CSE & Data Science.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Germany’s top-ranked technical university, known as the "Entrepreneurial University" with close ties to BMW, Siemens, and SAP.',
      },
      {
        id: 'u-2',
        countryId: 'c-de',
        name: 'Ludwig Maximilian University of Munich (LMU)',
        slug: 'lmu-munich',
        type: 'Public',
        qsRanking: 54,
        cityName: 'Munich',
        logoUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€152 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.lmu.de/en/',
        admissionReqSummary: 'High academic standing, IELTS 7.0 for English Master, APS certificate for Indian students.',
        degrees: 'Bachelor, Master, PhD',
        description: 'One of Europe’s premier research institutions with over 500 years of academic distinction across Medicine, Natural Sciences, and Humanities.',
      },
      {
        id: 'u-3',
        countryId: 'c-de',
        name: 'RWTH Aachen University',
        slug: 'rwth-aachen-university',
        type: 'Public',
        qsRanking: 99,
        cityName: 'Aachen',
        logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€315 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.rwth-aachen.de/cms/~a/ROOT/l/en/',
        admissionReqSummary: 'Strong technical credit alignment (Subject matching 100%), GRE General recommended.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Largest technical university in Germany and part of the TU9 alliance. Renowned worldwide for Mechanical, Automotive, and Electrical Engineering.',
      },
      {
        id: 'u-4',
        countryId: 'c-de',
        name: 'Technical University of Berlin (TU Berlin)',
        slug: 'tu-berlin',
        type: 'Public',
        qsRanking: 154,
        cityName: 'Berlin',
        logoUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€308 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.tu.berlin/en/',
        admissionReqSummary: 'Bachelor degree in relevant domain, IELTS 6.5+, Uni-Assist VPD requirement.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Member of TU9 situated in the vibrant capital of Germany, offering cutting-edge programs in CS, AI, and Urban Planning.',
      },
      {
        id: 'u-5',
        countryId: 'c-de',
        name: 'Karlsruhe Institute of Technology (KIT)',
        slug: 'kit-karlsruhe',
        type: 'Public',
        qsRanking: 102,
        cityName: 'Karlsruhe',
        logoUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€1,500 / semester',
        tuitionFee: '€3,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.kit.edu/english/',
        admissionReqSummary: 'High math & physics aptitude, German B2 or IELTS 6.5 depending on track.',
        degrees: 'Bachelor, Master, PhD',
        description: 'The Research University in the Helmholtz Association, globally renowned for Energy Tech, Computer Science, and Engineering.',
      },
      {
        id: 'u-6',
        countryId: 'c-de',
        name: 'Humboldt University of Berlin',
        slug: 'humboldt-university-berlin',
        type: 'Public',
        qsRanking: 126,
        cityName: 'Berlin',
        logoUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€315 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.hu-berlin.de/en',
        admissionReqSummary: 'Strong academic record, statement of purpose, English proficiency C1 for social sciences.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Alma mater of Albert Einstein and Max Planck, leading world research in Economics, Life Sciences, and Philosophy.',
      },
      {
        id: 'u-7',
        countryId: 'c-de',
        name: 'Freie Universitaet Berlin (FU Berlin)',
        slug: 'freie-universitaet-berlin',
        type: 'Public',
        qsRanking: 98,
        cityName: 'Berlin',
        logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€311 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.fu-berlin.de/en/',
        admissionReqSummary: 'Strong academic record, C1 English for English programs, APS required.',
        degrees: 'Bachelor, Master, PhD',
        description: 'One of Germany\'s top liberal arts universities, QS #98 globally, excelling in Political Science and Humanities.',
      },
      {
        id: 'u-8',
        countryId: 'c-de',
        name: 'Heidelberg University (Ruprecht-Karls-Universitaet)',
        slug: 'heidelberg-university',
        type: 'Public',
        qsRanking: 87,
        cityName: 'Heidelberg',
        logoUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€1,500 / semester',
        tuitionFee: '€3,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.uni-heidelberg.de/en/',
        admissionReqSummary: 'Exceptional academic record, APS certificate, IELTS 7.0 for English programs.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Germany\'s oldest university (founded 1386), ranked #87 globally. World-renowned for Medicine and Life Sciences.',
      },
      {
        id: 'u-9',
        countryId: 'c-de',
        name: 'University of Stuttgart',
        slug: 'university-of-stuttgart',
        type: 'Public',
        qsRanking: 368,
        cityName: 'Stuttgart',
        logoUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€1,500 / semester',
        tuitionFee: '€3,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.uni-stuttgart.de/en/',
        admissionReqSummary: 'Strong engineering background, IELTS 6.5 or German B2.',
        degrees: 'Bachelor, Master, PhD',
        description: 'TU9 member based in Germany\'s automotive heartland, home to Mercedes-Benz and Porsche HQs.',
      },
      {
        id: 'u-10',
        countryId: 'c-de',
        name: 'Goethe University Frankfurt',
        slug: 'goethe-university-frankfurt',
        type: 'Public',
        qsRanking: 310,
        cityName: 'Frankfurt',
        logoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€315 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.goethe-university-frankfurt.de/en/',
        admissionReqSummary: 'Bachelor degree in relevant field, IELTS 6.5+, APS certificate.',
        degrees: 'Bachelor, Master, PhD',
        description: 'A civic university in Germany\'s financial capital. Acclaimed for Finance, Economics, and Neuroscience.',
      },
      {
        id: 'u-11',
        countryId: 'c-de',
        name: 'University of Hamburg',
        slug: 'university-of-hamburg',
        type: 'Public',
        qsRanking: 276,
        cityName: 'Hamburg',
        logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€345 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.uni-hamburg.de/en.html',
        admissionReqSummary: 'Bachelor in relevant discipline, IELTS 6.5, APS certificate.',
        degrees: 'Bachelor, Master, PhD',
        description: 'North Germany\'s largest university with focus on Earth Sciences, Meteorology, and Law.',
      },
      {
        id: 'u-12',
        countryId: 'c-de',
        name: 'University of Cologne (Universitaet zu Koeln)',
        slug: 'university-of-cologne',
        type: 'Public',
        qsRanking: 215,
        cityName: 'Cologne',
        logoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€293 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://portal.uni-koeln.de/en/',
        admissionReqSummary: 'Bachelor in related field, IELTS 6.5, APS certificate.',
        degrees: 'Bachelor, Master, PhD',
        description: 'One of Germany\'s largest universities with over 52,000 students, renowned for Management and Law.',
      },
      {
        id: 'u-13',
        countryId: 'c-de',
        name: 'University of Goettingen (Georg-August-Universitaet)',
        slug: 'university-of-gottingen',
        type: 'Public',
        qsRanking: 296,
        cityName: 'Gottingen',
        logoUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€380 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.uni-goettingen.de/en/',
        admissionReqSummary: 'Strong academic credentials, IELTS 6.5, APS required.',
        degrees: 'Bachelor, Master, PhD',
        description: 'A historic research university in Lower Saxony with 47 Nobel Prize-winning alumni.',
      },
      {
        id: 'u-14',
        countryId: 'c-de',
        name: 'TU Dresden (Technische Universitaet Dresden)',
        slug: 'tu-dresden-technische',
        type: 'Public',
        qsRanking: 267,
        cityName: 'Dresden',
        logoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€258 / semester',
        tuitionFee: '€0 (Tuition Free)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://tu-dresden.de/en/',
        admissionReqSummary: 'Relevant Bachelor degree, IELTS 6.5 or German B2, APS certificate.',
        degrees: 'Bachelor, Master, PhD',
        description: 'TU9 member in Dresden, excelling in Mechanical Engineering and Microelectronics.',
      },
      {
        id: 'u-15',
        countryId: 'c-de',
        name: 'University of Mannheim',
        slug: 'university-of-mannheim',
        type: 'Public',
        qsRanking: 521,
        cityName: 'Mannheim',
        logoUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€1,500 / semester',
        tuitionFee: '€3,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.uni-mannheim.de/en/',
        admissionReqSummary: 'IELTS 7.0 for English programs, strong GPA in Business/Economics.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Germany\'s #1 business school located in a historic baroque palace.',
      },
      {
        id: 'u-16',
        countryId: 'c-de',
        name: 'Frankfurt School of Finance and Management',
        slug: 'frankfurt-school-of-finance',
        type: 'Private',
        qsRanking: 355,
        cityName: 'Frankfurt',
        logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€4,000 - €8,000 / semester',
        tuitionFee: '€8,000 - €16,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.frankfurt-school.de/en/',
        admissionReqSummary: 'IELTS 6.5, relevant Bachelor in Business, GMAT recommended.',
        degrees: 'Bachelor, Master',
        description: 'Triple-accredited private business school in Germany\'s financial capital.',
      },
      {
        id: 'u-17',
        countryId: 'c-de',
        name: 'ESMT Berlin (European School of Management and Technology)',
        slug: 'esmt-berlin',
        type: 'Private',
        qsRanking: 471,
        cityName: 'Berlin',
        logoUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€5,000 - €9,000 / semester',
        tuitionFee: '€10,000 - €18,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://esmt.berlin/en',
        admissionReqSummary: 'IELTS 7.0, professional experience preferred.',
        degrees: 'Master',
        description: 'A leading European business school founded by 25 global companies.',
      },
    ],
    requirements: [
      {
        id: 'r-1',
        degreeLevel: 'Master',
        academicReq: '4-year Bachelor degree (B.Tech / B.E / B.Sc) from H+ recognized university on Anabin database.',
        minCGPA: '7.5 / 10 (German Grade 2.5 or better)',
        ieltsScore: '6.5 overall (Min 6.0 in each band)',
        toeflScore: '88 iBT',
        germanReq: 'A1/A2 recommended for living; C1 required for German tracks.',
        apsRequired: true,
        greGmatReq: 'GRE required for TUM CS & Data Science (Quant 164+)',
        portfolioReq: 'Architecture / Fine Arts only',
        experienceReq: 'Work experience appreciated but not mandatory',
        notes: 'Stage 1 Aptitude Assessment evaluates CGPA & Credit match.',
      },
      {
        id: 'r-2',
        degreeLevel: 'Bachelor',
        academicReq: '12th Grade Board Exam + Studienkolleg (Feststellungsprüfung) OR 1 year recognized Indian degree.',
        minCGPA: '85% in 12th Board Exams (CBSE/ISC)',
        ieltsScore: '6.5',
        toeflScore: '80',
        germanReq: 'B2 / C1 TestDaF mandatory for most Bachelor tracks.',
        apsRequired: true,
        greGmatReq: 'Not applicable',
        portfolioReq: 'Not applicable',
        experienceReq: 'None',
        notes: 'Indian students with JEE Advanced rank can bypass Studienkolleg.',
      },
      {
        id: 'r-3',
        degreeLevel: 'PhD',
        academicReq: 'Master degree (M.Tech/M.Sc) with published research capability.',
        minCGPA: '8.0 / 10',
        ieltsScore: '7.0',
        toeflScore: '95',
        germanReq: 'A1 basic German',
        apsRequired: true,
        greGmatReq: 'Optional',
        portfolioReq: 'Research Proposal (15-20 pages)',
        experienceReq: 'Prior published research papers highly preferred.',
        notes: 'Direct supervisor agreement required prior to enrollment.',
      },
    ],
    documents: [
      { id: 'd-1', title: 'Valid Passport', category: 'General', description: 'Original passport with at least 12 months validity.', purpose: 'Identity verification for APS, Uni-Assist & Visa.', commonMistakes: 'Expired passport, name mismatch with marksheets.', isMandatory: true, stage: 'APS' },
      { id: 'd-2', title: 'Academic Transcripts & Mark Sheets', category: 'Academic', description: 'Official consolidated semester marksheets.', purpose: 'Academic evaluation by APS and Universities.', commonMistakes: 'Unapproved online portal screenshots.', isMandatory: true, stage: 'APS' },
      { id: 'd-3', title: 'Bachelor / School Degree Certificate', category: 'Academic', description: 'Original Degree Certificate or Provisional Certificate.', purpose: 'Proof of degree completion.', commonMistakes: 'Submitting course completion letter without degree certificate.', isMandatory: true, stage: 'APS' },
      { id: 'd-4', title: 'APS Certificate (Akademische Prüfstelle)', category: 'Academic', description: 'Verification certificate confirming authenticity of Indian academic documents.', purpose: 'Mandatory prerequisite for German student visa in India.', commonMistakes: 'Delaying application. Takes 4-8 weeks.', isMandatory: true, stage: 'Visa' },
      { id: 'd-5', title: 'Curriculum Vitae (Tabular CV)', category: 'Academic', description: 'Europass style chronological CV without gaps.', purpose: 'Evaluation of work experience & projects.', commonMistakes: 'Unexplained gaps in education/career.', isMandatory: true, stage: 'University Application' },
      { id: 'd-6', title: 'Statement of Purpose (SOP)', category: 'Academic', description: '1-2 page tailored letter explaining motivation and academic fit.', purpose: 'Evaluating candidate academic alignment.', commonMistakes: 'Generic SOP reused across multiple universities.', isMandatory: true, stage: 'University Application' },
      { id: 'd-7', title: 'Letters of Recommendation (LOR)', category: 'Academic', description: '2 Letters on official university letterhead.', purpose: 'Academic appraisal of candidate capability.', commonMistakes: 'Missing official letterhead or stamp.', isMandatory: true, stage: 'University Application' },
      { id: 'd-8', title: 'English Score Card (IELTS / TOEFL)', category: 'Academic', description: 'Official score card (IELTS Academic 6.5+ or TOEFL 88+).', purpose: 'Proof of English language proficiency.', commonMistakes: 'Submitting IELTS General module.', isMandatory: true, stage: 'University Application' },
      { id: 'd-9', title: 'Blocked Account Confirmation (Sperrkonto)', category: 'Financial', description: 'Official confirmation showing €11,904 deposited.', purpose: 'Proof of financial means for 1 year in Germany.', commonMistakes: 'Transferring incorrect buffer amount.', isMandatory: true, stage: 'Visa' },
      { id: 'd-10', title: 'Health Insurance Certificate', category: 'Visa', description: 'Incoming travel insurance + German health insurance confirmation (TK/Expatrio).', purpose: 'Medical coverage required for visa and university enrollment.', commonMistakes: 'Non-compliant insurance provider.', isMandatory: true, stage: 'Visa' },
    ],
    apsGuides: [
      {
        id: 'aps-1',
        title: 'Complete APS Certificate Guide for Germany',
        eligibility: 'All Indian nationals with degrees/diplomas applying for higher education in Germany.',
        requiredDocsJson: JSON.stringify([
          'Printed and signed APS application form',
          'Copy of Aadhaar Card linked with mobile number',
          'Copy of valid Passport (first and last page)',
          'Class 10th Marksheet & Certificate',
          'Class 12th Marksheet & Certificate',
          'Bachelor Marksheets (All semesters)',
          'Bachelor Degree / Provisional Certificate',
          'Language Proficiency Certificate (IELTS/TOEFL)',
          'Bank Payment Receipt of ₹18,000 APS Fee',
          'University Professor Email & Student Portal Credentials',
        ]),
        feeAmount: '18,000',
        feeCurrency: 'INR',
        timelineWeeks: '4 - 8 weeks',
        trackingUrl: 'https://aps-india.de/',
        officialPortalUrl: 'https://aps-india.de/',
        applicationStepsJson: JSON.stringify([
          'Register online on official APS India portal (aps-india.de).',
          'Fill in personal, educational, and university details.',
          'Pay processing fee of ₹18,000 via online bank transfer.',
          'Gather self-attested document copies.',
          'Courier printed application form + document dossier to APS Office New Delhi.',
          'APS team verifies credentials with your Indian university.',
          'Digital APS Certificate is issued via email upon verification.',
        ]),
        faqsJson: JSON.stringify([
          { q: 'Is APS mandatory for all Indian students?', a: 'Yes, mandatory for all Indian student visas since Nov 2022.' },
          { q: 'Does APS certificate expire?', a: 'No, valid indefinitely as long as your qualifications remain unchanged.' },
          { q: 'What if university email verification is delayed?', a: 'Provide student portal credentials in your application so APS can verify directly.' },
        ]),
      },
    ],
    visas: [
      {
        id: 'v-1',
        visaType: 'National Student Visa (Category D)',
        feeAmount: '€75 (~₹6,800)',
        processingTimeWeeks: '4 - 8 weeks',
        biometricsInfo: 'Mandatory biometrics taken at VFS Global center.',
        embassyPortalUrl: 'https://india.diplo.de/in-en/service/-/2552164',
        stepsJson: JSON.stringify([
          'Receive official University Admission Letter (Zulassungsbescheid).',
          'Obtain digital APS Certificate.',
          'Open Blocked Account (Sperrkonto) and deposit €11,904.',
          'Obtain compliant Health Insurance confirmation.',
          'Book VFS Global appointment for German Student Visa category.',
          'Prepare VIDEX application form and 2 identical document sets.',
          'Attend VFS appointment for biometric capture.',
          'Track passport via VFS portal until stamped visa passport delivery.',
        ]),
        requiredDocsJson: JSON.stringify([
          'Valid Passport + 2 photocopies',
          '2 Completed VIDEX application forms signed',
          '3 Biometric passport photographs (35mm x 45mm, white background)',
          'University Admission Letter / Offer Letter',
          'APS Certificate (Original)',
          'Proof of Blocked Account (€11,904 confirmation)',
          'Proof of Health Insurance',
          'Curriculum Vitae (CV) & Motivation Letter',
          'Academic Marksheets & Degree Certificates',
          'Proof of English/German Language Proficiency',
        ]),
        rejectionReasonsJson: JSON.stringify([
          'Incomplete financial proof or unverified blocked account source.',
          'Weak or generic Motivation Letter showing lack of clear academic intent.',
          'Submitting non-APS certified academic marksheets.',
          'Mismatch between prior study background and proposed Master degree without justification.',
          'Lack of basic language skills required for the course.',
        ]),
      },
    ],
    timelines: [
      { id: 't-1', monthMark: '-12 Months', title: 'Research & Language Prep', description: 'Explore DAAD course catalog, shortlist target universities, and start IELTS and German language study.', actionsJson: JSON.stringify(['Browse DAAD.de database', 'Begin IELTS prep', 'Register for German A1 at Goethe Institute']), icon: 'Search', order: 1 },
      { id: 't-2', monthMark: '-10 Months', title: 'Language Tests', description: 'Take IELTS Academic (Aim 6.5+) and GRE for top CS programs.', actionsJson: JSON.stringify(['Take IELTS exam', 'Order official test score reports']), icon: 'Award', order: 2 },
      { id: 't-3', monthMark: '-8 Months', title: 'APS Certification', description: 'Apply for APS India certification early! Courier documents to Delhi office.', actionsJson: JSON.stringify(['Register on aps-india.de', 'Pay ₹18,000 fee', 'Send physical document bundle']), icon: 'FileCheck', order: 3 },
      { id: 't-4', monthMark: '-6 Months', title: 'Uni-Assist & University Applications', description: 'Submit applications via Uni-Assist or university direct portals.', actionsJson: JSON.stringify(['Create Uni-Assist account', 'Upload SOP, LOR, and transcripts', 'Pay Uni-Assist evaluation fees']), icon: 'Send', order: 4 },
      { id: 't-5', monthMark: '-4 Months', title: 'Admission & Blocked Account', description: 'Receive offer letter. Immediately open Blocked Account and transfer €11,904.', actionsJson: JSON.stringify(['Accept university offer', 'Open Expatrio/Fintiba account', 'Transfer blocked funds & buffer']), icon: 'Landmark', order: 5 },
      { id: 't-6', monthMark: '-3 Months', title: 'Health Insurance & Visa Slot', description: 'Set up German health insurance and book VFS Student Visa slot.', actionsJson: JSON.stringify(['Activate TK Health Insurance package', 'Book VFS appointment', 'Fill VIDEX online visa form']), icon: 'ShieldCheck', order: 6 },
      { id: 't-7', monthMark: '-2 Months', title: 'Visa Interview & Accommodation', description: 'Attend VFS biometric appointment. Start hunting for student dorms & WGs.', actionsJson: JSON.stringify(['Attend VFS visa appointment', 'Apply to Studierendenwerk dorm queue', 'Search WG-Gesucht.de']), icon: 'Home', order: 7 },
      { id: 't-8', monthMark: '-1 Month', title: 'Flight Booking & Packing', description: 'Receive stamped visa passport, book student flight ticket, and pack essential documents.', actionsJson: JSON.stringify(['Book one-way flight ticket', 'Exchange EUR cash (€500-1000)', 'Pack forex card & document originals']), icon: 'Plane', order: 8 },
      { id: 't-9', monthMark: '0 Month (Arrival)', title: 'Welcome to Germany!', description: 'Complete City Registration (Anmeldung), activate bank account payout, and complete University Enrollment.', actionsJson: JSON.stringify(['Complete City Registration (Anmeldung)', 'Activate local bank account payout', 'Attend Orientation Week']), icon: 'MapPin', order: 9 },
    ],
    scholarships: [
      { id: 's-1', countryId: 'c-de', title: 'DAAD EPOS Postgraduate Scholarship', providerType: 'DAAD', fundingAmount: '€934 / month + Travel Stipend + Health Insurance', degreeLevel: 'Master, PhD', deadline: 'August - October', eligibility: 'Applicants with at least 2 years work experience.', officialWebsite: 'https://www.daad.de/en/', description: 'Full funding for postgraduate courses in engineering, environmental sciences, and public health.' },
      { id: 's-2', countryId: 'c-de', title: 'Deutschlandstipendium', providerType: 'Government', fundingAmount: '€300 / month', degreeLevel: 'Bachelor, Master', deadline: 'July - September', eligibility: 'High academic achievers registered at participating German universities.', officialWebsite: 'https://www.deutschlandstipendium.de/', description: 'Merit-based scholarship awarded directly by universities.' },
      { id: 's-3', countryId: 'c-de', title: 'Heinrich Böll Foundation Scholarships', providerType: 'Private', fundingAmount: '€934 / month + Allowances', degreeLevel: 'Master, PhD', deadline: 'March 1 & September 1', eligibility: 'Students with outstanding academic records who embody green political values.', officialWebsite: 'https://www.boell.de/en/scholarships', description: 'Awards around 1,400 scholarships per year to international postgraduate students.' },
      { id: 's-4', countryId: 'c-de', title: 'Konrad-Adenauer-Stiftung (KAS) Scholarship', providerType: 'Private', fundingAmount: '€861 - €1,200 / month', degreeLevel: 'Master, PhD', deadline: 'July 15', eligibility: 'Under 30 years old, strong academic performance, active voluntary work.', officialWebsite: 'https://www.kas.de/', description: 'Aimed at international students committed to democracy and civic engagement.' },
      { id: 's-5', countryId: 'c-de', title: 'Erasmus+ Joint Master Degrees', providerType: 'University', fundingAmount: '€1,400 / month + Full Tuition Coverage', degreeLevel: 'Master', deadline: 'January - March', eligibility: 'Global applicants holding relevant Bachelor degree.', officialWebsite: 'https://ec.europa.eu/programmes/erasmus-plus/', description: 'Prestigious EU mobility scholarship allowing study across 2-3 European universities.' },
    ],
    livingCosts: [
      { id: 'lc-1', cityName: 'Munich', rent: 650, food: 250, transport: 49, utilities: 110, internet: 30, entertainment: 120, monthlyTotal: 1209, description: 'Highest cost of living in Germany, compensated by high concentrations of tech industry jobs.' },
      { id: 'lc-2', cityName: 'Berlin', rent: 550, food: 230, transport: 49, utilities: 95, internet: 28, entertainment: 110, monthlyTotal: 1062, description: 'Vibrant startup capital with diverse cultural scene.' },
      { id: 'lc-3', cityName: 'Aachen', rent: 420, food: 200, transport: 0, utilities: 85, internet: 25, entertainment: 80, monthlyTotal: 810, description: 'Extremely student-friendly town near Dutch border. Free transit ticket.' },
      { id: 'lc-4', cityName: 'Karlsruhe', rent: 450, food: 210, transport: 0, utilities: 90, internet: 25, entertainment: 85, monthlyTotal: 860, description: 'Sunny technology hub with moderate rents around KIT.' },
    ],
    accommodations: [
      { id: 'acc-1', type: 'Student Dorm (Studierendenwerk)', avgCostRange: '€230 - €400 / month', depositRequired: '1 - 2 months rent', bookingPortals: 'Studierendenwerk university website', tips: 'Apply to waiting list immediately upon receiving application confirmation!', pros: 'Cheapest option, fully furnished, close to campus.', cons: 'Long waiting lists in major cities.' },
      { id: 'acc-2', type: 'WG (Shared Flat)', avgCostRange: '€350 - €650 / month', depositRequired: '2 - 3 months rent', bookingPortals: 'WG-Gesucht.de, Kleinanzeigen.de', tips: 'Write personalized messages in German/English introducing your lifestyle.', pros: 'Most popular option for social life, flexible location.', cons: 'Casting interviews can be competitive.' },
      { id: 'acc-3', type: 'Private Apartment', avgCostRange: '€600 - €1,200 / month', depositRequired: '3 months cold rent', bookingPortals: 'Immobilienscout24.de, HousingAnywhere', tips: 'Ensure landlord provides Wohnungsgeberbestätigung for Anmeldung.', pros: 'Complete privacy, quiet environment.', cons: 'Expensive, often unfurnished.' },
    ],
    partTimeJobs: [
      { id: 'pt-1', allowedHours: '140 full days (280 half days) per calendar year', minWage: '€13.90 / hour', miniJobCap: '€556 / month (Tax-free limit)', taxRules: 'Mini-jobs under €556/month are tax-free.', popularJobsJson: JSON.stringify(['Working Student (Werkstudent IT/Engg): €14 - €22/hr', 'HiWi Research Assistant: €13 - €16/hr', 'English Tutor: €15 - €25/hr', 'Supermarket Cashier: €13 - €15/hr', 'Delivery Rider: €13 - €16/hr']), semesterRules: 'Max 20 hours per week during active semester.', holidayRules: 'Full-time work allowed during official semester break.', jobPortalsJson: JSON.stringify(['Zenjob App', 'StepStone.de', 'Indeed Germany', 'Linkedin Student Jobs']) },
    ],
    insurances: [
      { id: 'ins-1', type: 'Public', providerName: 'Techniker Krankenkasse (TK)', monthlyCost: '~€125 - €130 / month', requirements: 'Mandatory for degree students under 30.', coverageDetails: '100% full coverage for doctors, hospitals, and prescriptions.', pros: 'Voted #1 health insurance, English app.', cons: 'Higher monthly premium than private alternative.', recommendedFor: 'All degree students under 30 looking for comprehensive coverage.' },
      { id: 'ins-2', type: 'Public', providerName: 'Barmer / AOK', monthlyCost: '~€125 - €130 / month', requirements: 'Mandatory for students under 30.', coverageDetails: 'Comprehensive statutory medical & emergency transport.', pros: 'Extensive physical campus branch network.', cons: 'Slightly slower digital app experience.', recommendedFor: 'Students who prefer local physical service branches.' },
      { id: 'ins-3', type: 'Private', providerName: 'Mawista / Educare24', monthlyCost: '~€35 - €70 / month', requirements: 'For Studienkolleg, language course students, or over 30.', coverageDetails: 'Basic emergency medical treatment.', pros: 'Very cheap monthly premium.', cons: 'Does not cover pre-existing conditions or routine checkups.', recommendedFor: 'Preparatory course students prior to university matriculation.' },
    ],
    officialResources: [
      { id: 'r-1', title: 'DAAD (German Academic Exchange Service)', category: 'University', url: 'https://www.daad.de/en/', description: 'Official database of all English-taught programs in Germany.', badgeText: 'Official Portal' },
      { id: 'r-2', title: 'APS India (Akademische Prüfstelle)', category: 'Embassy', url: 'https://aps-india.de/', description: 'Official verification gatekeeper for Indian academic certificates.', badgeText: 'Mandatory' },
      { id: 'r-3', title: 'Uni-Assist e.V.', category: 'University', url: 'https://www.uni-assist.de/en/', description: 'Central evaluation portal processing international applications.', badgeText: 'Application Portal' },
      { id: 'r-4', title: 'German Embassy India (Diplo.de)', category: 'Visa', url: 'https://india.diplo.de/in-en/service/-/2552164', description: 'Official visa guidelines and embassy appointments.', badgeText: 'Official Embassy' },
      { id: 'r-5', title: 'Make it in Germany', category: 'General', url: 'https://www.make-it-in-germany.com/en/', description: 'Official portal of the German Federal Government for students and professionals.', badgeText: 'Gov Portal' },
      { id: 'r-6', title: 'WG-Gesucht Housing Portal', category: 'Housing', url: 'https://www.wg-gesucht.de/', description: 'Germany’s largest search portal for student shared flats.', badgeText: 'Housing' },
    ],
    faqs: [
      { id: 'faq-1', question: 'Are public universities in Germany really tuition-free?', answer: 'Yes! Public universities in 15 out of 16 German federal states charge €0 tuition fees for both EU and non-EU international students. You only pay a minor semester contribution (€150–€400) which includes a public transport pass.', category: 'Admission', tags: 'tuition, free' },
      { id: 'faq-2', question: 'What is a Blocked Account (Sperrkonto) and how much is required?', answer: 'A Blocked Account is a mandatory proof of financial resources required for the German student visa. Required amount is €11,904 per year (€992 per month released to your checking account).', category: 'Blocked Account', tags: 'blocked account, money' },
      { id: 'faq-3', question: 'What is the APS Certificate and is it mandatory for Indian students?', answer: 'Yes, the APS Certificate issued by Akademische Prüfstelle in New Delhi is mandatory for all Indian student visas since Nov 2022.', category: 'APS', tags: 'aps, certificate' },
      { id: 'faq-4', question: 'Can I work part-time while studying in Germany?', answer: 'Yes! Non-EU international students can legally work up to 140 full days or 280 half days per calendar year. Minimum wage is €12.41 per hour.', category: 'Jobs', tags: 'work, part-time' },
      { id: 'faq-5', question: 'What is the Post-Study Work Visa in Germany?', answer: 'After graduating from a German university, international students can extend their residence permit for up to 18 months to search for a job related to their degree.', category: 'Visa', tags: 'post study, visa' },
    ],
  };
}

export function getFallbackAustriaData(): Country {
  return {
    id: 'c-at',
    name: 'Austria',
    slug: 'austria',
    code: 'AT',
    flagEmoji: '🇦🇹',
    avgTuition: '€726.72 / semester (non-EU/EEA)',
    avgLivingCost: '€950 - €1,300 / month',
    workHours: '20 hours / week (during semester)',
    popularIntake: 'Winter (Oct) & Summer (Mar)',
    shortDesc: 'A welcoming central-European study hub with affordable public university tuition (€726.72/semester for non-EU), no APS requirement, ÖGK health insurance at just €78.84/month, and vibrant student cities like Vienna, Graz, and Innsbruck.',
    isComplete: true,
    capital: 'Vienna',
    currency: 'Euro (€)',
    language: 'German (English for many Masters)',
    population: '9.1 Million',
    intStudentsCount: '90,000+',
    semesterContrib: '~€25.20 / semester (ÖH Student Union Fee)',
    blockedAccountAmt: '€722.58 / month (under 24) | €1,308.39 / month (24+) — NOT mandatory as Sperrkonto',
    minWage: 'No statutory minimum — Kollektivverträge (~€1,700/month avg)',
    publicUnivCount: 22,
    privateUnivCount: 14,
    topCities: JSON.stringify(['Vienna', 'Graz', 'Innsbruck', 'Salzburg', 'Linz', 'Klagenfurt']),
    popularCourses: JSON.stringify(['Computer Science', 'Business & Economics', 'Medicine', 'Music & Arts', 'Engineering', 'Tourism Management']),
    climate: 'Continental (Alpine winters, warm summers: -5°C to 28°C)',
    timeDiff: 'UTC+1 (CET) / UTC+2 (CEST)',
    safetyIndex: '80.1 (Very Safe)',
    cities: [
      { id: 'at-c-1', countryId: 'c-at', name: 'Vienna', avgRent: 560, avgFood: 250, avgTransport: 30, avgUtilities: 100, avgInternet: 25, avgEntertainment: 110, totalMonthly: 1075, isPopular: true },
      { id: 'at-c-2', countryId: 'c-at', name: 'Graz', avgRent: 400, avgFood: 210, avgTransport: 40, avgUtilities: 85, avgInternet: 22, avgEntertainment: 80, totalMonthly: 837, isPopular: true },
      { id: 'at-c-3', countryId: 'c-at', name: 'Innsbruck', avgRent: 450, avgFood: 220, avgTransport: 35, avgUtilities: 90, avgInternet: 22, avgEntertainment: 85, totalMonthly: 902, isPopular: true },
      { id: 'at-c-4', countryId: 'c-at', name: 'Salzburg', avgRent: 480, avgFood: 230, avgTransport: 35, avgUtilities: 90, avgInternet: 22, avgEntertainment: 90, totalMonthly: 947, isPopular: true },
    ],
    universities: [
      {
        id: 'at-u-1',
        countryId: 'c-at',
        name: 'University of Vienna (Universität Wien)',
        slug: 'university-of-vienna',
        type: 'Public',
        qsRanking: 140,
        cityName: 'Vienna',
        logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€726.72 + €25.20 ÖH fee / semester (Non-EU/EEA)',
        tuitionFee: '€1,453.44 / year (Non-EU/EEA)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.univie.ac.at/en/',
        admissionReqSummary: 'Bachelor degree with good GPA, IELTS 6.5+ or equivalent, German B2 for German-taught programs.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Austria\'s largest and oldest university (founded 1365), ranked #140 globally (QS 2027). World-renowned for Law, Humanities, Natural Sciences, and Social Sciences.',
      },
      {
        id: 'at-u-2',
        countryId: 'c-at',
        name: 'TU Wien (Vienna University of Technology)',
        slug: 'tu-wien',
        type: 'Public',
        qsRanking: 191,
        cityName: 'Vienna',
        logoUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€726.72 + €25.20 ÖH fee / semester (Non-EU/EEA)',
        tuitionFee: '€1,453.44 / year (Non-EU/EEA)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.tuwien.at/en/',
        admissionReqSummary: 'Bachelor in relevant STEM discipline, IELTS 6.0+ for English programs, proof of mathematics proficiency.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Austria\'s premier technical university, ranked #191 globally (QS 2027). Renowned for Computer Science, Electrical Engineering, and Architecture. Strong industry partnerships with Siemens, Bosch, and AVL.',
      },
      {
        id: 'at-u-3',
        countryId: 'c-at',
        name: 'WU Wien (Vienna University of Economics and Business)',
        slug: 'wu-wien',
        type: 'Public',
        qsRanking: 631,
        cityName: 'Vienna',
        logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€726.72 + €25.20 ÖH fee / semester (Non-EU/EEA)',
        tuitionFee: '€1,453.44 / year (Non-EU/EEA)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.wu.ac.at/en/',
        admissionReqSummary: 'Bachelor in Business/Economics, IELTS 6.5+, strong quantitative background.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Europe\'s largest business university ranked #69 globally for Business & Management (QS Subject 2026). Triple-accredited (AACSB, EQUIS, AMBA). Housed in a striking modern campus designed by Zaha Hadid.',
      },
      {
        id: 'at-u-4',
        countryId: 'c-at',
        name: 'University of Graz (Karl-Franzens-Universität Graz)',
        slug: 'university-of-graz',
        type: 'Public',
        qsRanking: 651,
        cityName: 'Graz',
        logoUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€726.72 + €25.20 ÖH fee / semester (Non-EU/EEA)',
        tuitionFee: '€1,453.44 / year (Non-EU/EEA)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.uni-graz.at/en/',
        admissionReqSummary: 'Bachelor degree or equivalent, German B2 for German-taught programs, IELTS 6.0+ for English programs.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Second-largest Austrian university (founded 1585), located in Austria\'s second-largest city. Renowned for Natural Sciences, Social Sciences, and Law. Home to 4 Nobel Prize winners.',
      },
      {
        id: 'at-u-5',
        countryId: 'c-at',
        name: 'University of Innsbruck (Leopold-Franzens-Universität Innsbruck)',
        slug: 'university-of-innsbruck',
        type: 'Public',
        qsRanking: 701,
        cityName: 'Innsbruck',
        logoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€726.72 + €25.20 ÖH fee / semester (Non-EU/EEA)',
        tuitionFee: '€1,453.44 / year (Non-EU/EEA)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.uibk.ac.at/en/',
        admissionReqSummary: 'Bachelor in relevant field, IELTS 6.0+, German B2 for German-taught programs.',
        degrees: 'Bachelor, Master, PhD',
        description: 'Alpine university in the heart of the Tyrol mountains. World-class for Alpine Science, Political Science, and Physics. Exceptional quality of life in a scenic mountain city.',
      },
      {
        id: 'at-u-6',
        countryId: 'c-at',
        name: 'Graz University of Technology (TU Graz)',
        slug: 'tu-graz',
        type: 'Public',
        qsRanking: 521,
        cityName: 'Graz',
        logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€726.72 + €25.20 ÖH fee / semester (Non-EU/EEA)',
        tuitionFee: '€1,453.44 / year (Non-EU/EEA)',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.tugraz.at/en/home/',
        admissionReqSummary: 'Strong STEM background, IELTS 6.0+, mathematics aptitude test may be required.',
        degrees: 'Bachelor, Master, PhD',
        description: 'A leading technical university in Graz with strong industry ties to automotive companies (AVL, Magna). Top programs in Computer Science, Electrical Engineering, and Mechanical Engineering.',
      },
      {
        id: 'at-u-7',
        countryId: 'c-at',
        name: 'Webster Vienna Private University',
        slug: 'webster-vienna',
        type: 'Private',
        qsRanking: 1000,
        cityName: 'Vienna',
        logoUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=150&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&auto=format&fit=crop&q=80',
        semesterFee: '€5,800 - €8,500 / semester',
        tuitionFee: '€11,600 - €17,000 / year',
        hasEnglishPrograms: true,
        officialWebsite: 'https://www.webster.ac.at/',
        admissionReqSummary: 'Bachelor degree, IELTS 6.5+, strong academic record, personal statement.',
        degrees: 'Bachelor, Master',
        description: 'Fully accredited American university in Vienna offering 100% English-taught programs. Part of Webster University\'s global network. Ideal for students seeking US-style education in the heart of Europe.',
      },
    ],
    requirements: [
      {
        id: 'at-r-1',
        degreeLevel: 'Master',
        academicReq: '4-year Bachelor degree (B.Tech / B.E / B.Sc / B.Com) from a recognized university. Equivalence assessed by Austrian universities directly — no Anabin/Uni-Assist equivalent required.',
        minCGPA: '6.5 / 10 (varies by program; competitive programs require 7.5+)',
        ieltsScore: '6.5 overall (programs vary; some accept 6.0)',
        toeflScore: '79 iBT (minimum; most programs prefer 90+)',
        germanReq: 'B2 / C1 for German-taught programs; not required for 100% English-taught programs.',
        apsRequired: false,
        greGmatReq: 'Generally not required; GMAT recommended for WU Wien MBA programs.',
        portfolioReq: 'Required for Fine Arts, Architecture, and Design programs at University of Applied Arts Vienna.',
        experienceReq: 'Work experience generally not required; appreciated for specialized MBA programs.',
        notes: 'Austrian universities evaluate qualifications directly. No centralized portal like Uni-Assist — apply directly on the university\'s online admission portal. Start 6–9 months before the semester begins.',
      },
      {
        id: 'at-r-2',
        degreeLevel: 'Bachelor',
        academicReq: '12th Grade Board Certificate (CBSE/ISC 85%+) or equivalent. Non-EU students may need to complete a preparatory assessment (Ergänzungsprüfung) at the university.',
        minCGPA: '85% in 12th Board (for direct admission); or 1 year of recognized home-country university study.',
        ieltsScore: '6.0',
        toeflScore: '72 iBT',
        germanReq: 'B2 / C1 TestDaF required for German-taught Bachelor programs. A2 basic German recommended for daily life.',
        apsRequired: false,
        greGmatReq: 'Not applicable',
        portfolioReq: 'Required for creative/arts programs',
        experienceReq: 'None',
        notes: 'APS Certificate is NOT required for Austria — this is a Germany-specific requirement only. Austrian universities assess academic credentials directly.',
      },
      {
        id: 'at-r-3',
        degreeLevel: 'PhD',
        academicReq: 'Master degree (M.Tech / M.Sc / M.A) with strong academic record and research proposal.',
        minCGPA: '7.5 / 10',
        ieltsScore: '7.0',
        toeflScore: '90',
        germanReq: 'A2/B1 basic German often helpful; English PhD programs widely available.',
        apsRequired: false,
        greGmatReq: 'Not typically required',
        portfolioReq: 'Detailed Research Proposal (10–20 pages)',
        experienceReq: 'Published research papers or conference presentations are a strong advantage.',
        notes: 'Must secure a supervisor agreement (Betreuungsvereinbarung) from an Austrian professor before formal enrollment. Direct contact with professors recommended 6–12 months in advance.',
      },
    ],
    documents: [
      { id: 'at-d-1', title: 'Valid Passport', category: 'General', description: 'Original passport with at least 12 months validity beyond intended stay and 2 blank pages.', purpose: 'Identity verification for university application, visa, and residence permit.', commonMistakes: 'Expired passport, name mismatch with academic certificates.', isMandatory: true, stage: 'University Application' },
      { id: 'at-d-2', title: 'Academic Transcripts & Mark Sheets', category: 'Academic', description: 'Official consolidated semester marksheets and transcripts from your university registrar.', purpose: 'Academic evaluation by Austrian university admissions.', commonMistakes: 'Submitting unofficial printouts instead of official sealed transcripts.', isMandatory: true, stage: 'University Application' },
      { id: 'at-d-3', title: 'Bachelor / School Degree Certificate', category: 'Academic', description: 'Original degree certificate or provisional passing certificate.', purpose: 'Proof of degree completion required for Master program admission.', commonMistakes: 'Submitting course completion letter instead of the final degree certificate.', isMandatory: true, stage: 'University Application' },
      { id: 'at-d-4', title: 'English / German Language Certificate', category: 'Academic', description: 'IELTS Academic 6.5+ / TOEFL 79 iBT+ for English programs; TestDaF or ÖSD B2/C1 for German programs.', purpose: 'Proof of language proficiency required for program admission.', commonMistakes: 'Submitting IELTS General instead of IELTS Academic; expired test scores (valid 2 years).', isMandatory: true, stage: 'University Application' },
      { id: 'at-d-5', title: 'Statement of Purpose / Motivation Letter', category: 'Academic', description: '1–2 page letter explaining study motivation, program choice, and career goals.', purpose: 'Evaluating academic alignment and motivation.', commonMistakes: 'Generic SOP not tailored to specific Austrian university/program.', isMandatory: true, stage: 'University Application' },
      { id: 'at-d-6', title: 'Letters of Recommendation (LOR)', category: 'Academic', description: '2 letters on official letterhead from professors or relevant professional supervisors.', purpose: 'Academic appraisal for graduate program admission.', commonMistakes: 'Missing official stamp, email signature, or letterhead.', isMandatory: true, stage: 'University Application' },
      { id: 'at-d-7', title: 'Curriculum Vitae (CV)', category: 'Academic', description: 'Europass-style chronological CV without unexplained gaps.', purpose: 'Overview of educational and professional background.', commonMistakes: 'Gaps in chronology, inconsistent dates, missing contact information.', isMandatory: true, stage: 'University Application' },
      { id: 'at-d-8', title: 'Proof of Financial Means', category: 'Financial', description: 'Bank statement, scholarship letter, or Haftungserklärung (guarantor declaration) showing sufficient funds. Under 24: €722.58/month; 24+: €1,308.39/month. NOTE: A blocked account (Sperrkonto) is one accepted option — not mandatory.', purpose: 'Proof of ability to cover living costs in Austria.', commonMistakes: 'Providing only a blocked account without understanding that personal bank statements or a guarantor declaration are equally valid alternatives.', isMandatory: true, stage: 'Visa' },
      { id: 'at-d-9', title: 'University Admission / Acceptance Letter', category: 'Academic', description: 'Official conditional or unconditional offer letter from your Austrian university.', purpose: 'Key document for residence permit application at Austrian embassy.', commonMistakes: 'Using a conditional offer letter without fulfilling the conditions before visa application.', isMandatory: true, stage: 'Visa' },
      { id: 'at-d-10', title: 'Health Insurance Certificate', category: 'Visa', description: 'ÖGK student self-insurance (€78.84/month) or equivalent private insurance covering all risks in Austria.', purpose: 'Mandatory for residence permit — must cover entire planned stay.', commonMistakes: 'Short-term travel insurance that does not meet all-risks coverage requirement.', isMandatory: true, stage: 'Visa' },
    ],
    apsGuides: [], // APS Certificate is Germany-specific — NOT required for Austria
    visas: [
      {
        id: 'at-v-1',
        visaType: 'Visa D (National Visa) + Residence Permit – Student (Aufenthaltsbewilligung Studierende)',
        feeAmount: 'Visa D: ~€150 | Residence Permit: €218 (as of Jan 2026)',
        processingTimeWeeks: 'Visa D: 8–16 weeks | Residence Permit: 6 weeks–6 months',
        biometricsInfo: 'Biometrics required at Austrian Embassy/Consulate for Visa D application.',
        embassyPortalUrl: 'https://www.bmeia.gv.at/en/austrian-embassy-new-delhi/',
        stepsJson: JSON.stringify([
          'Receive official University Admission / Acceptance Letter from your Austrian university.',
          'Gather proof of financial means (bank statement, scholarship letter, or Haftungserklärung) — blocked account optional.',
          'Obtain ÖGK student health insurance or equivalent all-risks health coverage.',
          'Book appointment at the Austrian Embassy in New Delhi for Visa D application.',
          'Submit Visa D application with complete document dossier and biometrics.',
          'Receive Visa D (entry visa) — typically 8–16 weeks processing.',
          'Travel to Austria within Visa D validity period.',
          'Register your address within 3 days of arrival (Meldezettel at local Meldeamt).',
          'Apply for Residence Permit (Aufenthaltsbewilligung) at local immigration authority (Magistrat/Bezirkshauptmannschaft) — within 3 months of arrival.',
          'Complete university enrollment (Immatrikulation) and register for ÖGK health insurance.',
        ]),
        requiredDocsJson: JSON.stringify([
          'Valid Passport (original + 2 photocopies)',
          '3 Biometric passport photographs (35mm x 45mm, white background)',
          'University Admission / Acceptance Letter (original)',
          'Proof of Financial Means: bank statements (3 months), scholarship letter, OR Haftungserklärung guarantor declaration',
          'Proof of Health Insurance (all-risks, covering full stay in Austria)',
          'Completed Visa D application form',
          'Curriculum Vitae (CV)',
          'Academic Transcripts & Degree Certificates',
          'English / German Language Certificate',
          'Proof of accommodation booking in Austria (dorm confirmation or rental agreement)',
        ]),
        rejectionReasonsJson: JSON.stringify([
          'Insufficient financial proof — amounts below the required threshold (€722.58/month under 24, €1,308.39/month for 24+).',
          'Incomplete or expired health insurance that does not meet all-risks coverage standard.',
          'Missing or conditional university admission letter without proof of condition fulfillment.',
          'Inconsistency between stated study purpose and academic background without adequate explanation.',
          'Incomplete document dossier — particularly missing translation or notarization of required documents.',
        ]),
      },
    ],
    timelines: [
      { id: 'at-t-1', monthMark: '-12 Months', title: 'Research & Language Preparation', description: 'Explore Austrian universities via studyinaustria.at and OeAD portals. Shortlist 5–8 programs. Start German language preparation (A1/A2) and IELTS prep.', actionsJson: JSON.stringify(['Browse studyinaustria.at database', 'Shortlist universities by subject ranking', 'Begin IELTS / TestDaF preparation', 'Register for German A1 at Goethe Institut']), icon: 'Search', order: 1 },
      { id: 'at-t-2', monthMark: '-10 Months', title: 'Language Tests', description: 'Appear for IELTS Academic (aim 6.5+) or TestDaF (B2/C1 for German-taught programs). Order official score reports for submission.', actionsJson: JSON.stringify(['Take IELTS Academic exam', 'Order official test score reports', 'Prepare TestDaF if applying to German-taught programs']), icon: 'Award', order: 2 },
      { id: 'at-t-3', monthMark: '-8 Months', title: 'Document Preparation & SOP', description: 'Gather all academic documents, obtain official transcripts, write Statement of Purpose, and request Letters of Recommendation. No APS required for Austria.', actionsJson: JSON.stringify(['Request official transcripts from your university', 'Write tailored Statement of Purpose per university', 'Request 2 Letters of Recommendation from professors', 'Get documents translated if required']), icon: 'FileCheck', order: 3 },
      { id: 'at-t-4', monthMark: '-6 Months', title: 'University Direct Applications', description: 'Apply directly through each Austrian university\'s online admission portal — no centralized Uni-Assist equivalent. Deadlines: typically July 1–September 1 (Winter), November 1–February 1 (Summer).', actionsJson: JSON.stringify(['Create accounts on university admission portals', 'Upload SOP, LOR, transcripts, and language scores', 'Pay application fees if required (varies by university)']), icon: 'Send', order: 4 },
      { id: 'at-t-5', monthMark: '-4 Months', title: 'Admission Offer & Financial Proof', description: 'Receive admission letter. Prepare financial proof — gather bank statements, scholarship letter, or arrange Haftungserklärung (guarantor declaration). A blocked account is optional.', actionsJson: JSON.stringify(['Accept university offer', 'Gather 3 months of bank statements showing sufficient funds', 'OR arrange Haftungserklärung from guarantor', 'Contact university about dorm/student housing application']), icon: 'Landmark', order: 5 },
      { id: 'at-t-6', monthMark: '-3 Months', title: 'Health Insurance & Visa Appointment', description: 'Register for ÖGK student self-insurance (€78.84/month) or equivalent all-risks coverage. Book appointment at Austrian Embassy in New Delhi for Visa D application.', actionsJson: JSON.stringify(['Register for ÖGK student health insurance', 'Book Austrian Embassy New Delhi appointment', 'Complete Visa D application form', 'Prepare complete document dossier']), icon: 'ShieldCheck', order: 6 },
      { id: 'at-t-7', monthMark: '-2 Months', title: 'Visa D Application & Accommodation', description: 'Attend Austrian Embassy appointment for biometrics and Visa D submission. Begin housing search — apply to student dorms (Studentenheime) or search WG portals for shared flats.', actionsJson: JSON.stringify(['Attend Austrian Embassy appointment', 'Apply to Studentenheim (student dorm) waiting lists', 'Search WG-Zimmer.at and willhaben.at for shared flats', 'Confirm accommodation for arrival']), icon: 'Home', order: 7 },
      { id: 'at-t-8', monthMark: '-1 Month', title: 'Flight Booking & Preparation', description: 'Receive Visa D. Book flight to Vienna, Graz, or Innsbruck. Prepare essential documents and exchange EUR cash for first weeks.', actionsJson: JSON.stringify(['Book flight ticket', 'Exchange EUR cash (€500–€800)', 'Prepare essential documents in carry-on', 'Download the ÖGK app and city navigation apps']), icon: 'Plane', order: 8 },
      { id: 'at-t-9', monthMark: '0 Month (Arrival)', title: 'Welcome to Austria!', description: 'Register address (Meldezettel) within 3 days of arrival. Apply for Residence Permit at Magistrat within 3 months. Complete university enrollment (Immatrikulation) and activate ÖGK e-card.', actionsJson: JSON.stringify(['Register address at Meldeamt within 3 days', 'Apply for Residence Permit (Aufenthaltsbewilligung) at Magistrat', 'Complete university Immatrikulation', 'Activate ÖGK health insurance and get e-card']), icon: 'MapPin', order: 9 },
    ],
    scholarships: [
      { id: 'at-s-1', countryId: 'c-at', title: 'OeAD Ernst Mach Grant (Worldwide)', providerType: 'Government', fundingAmount: '€1,050 / month + travel allowance', degreeLevel: 'Master, PhD', deadline: 'February 1 (Annual)', eligibility: 'Non-European Master and PhD students and postdocs for research stays in Austria (1–9 months).', officialWebsite: 'https://oead.at/en/to-austria/grants-and-scholarships/', description: 'Austria\'s flagship OeAD government scholarship for incoming international students. Covers monthly stipend, travel costs, and health insurance contribution. Apply via grants.oead.at.' },
      { id: 'at-s-2', countryId: 'c-at', title: 'Austria Excellence Scholarship (OeAD)', providerType: 'Government', fundingAmount: '€1,050 / month + supplementary benefits', degreeLevel: 'Master, PhD', deadline: 'February 1', eligibility: 'Outstanding students from selected countries with superior academic record and research focus.', officialWebsite: 'https://oead.at/en/to-austria/grants-and-scholarships/', description: 'Prestigious scholarship for academically outstanding international students pursuing research-based degrees at Austrian universities.' },
      { id: 'at-s-3', countryId: 'c-at', title: 'Erasmus+ Joint Master Degrees', providerType: 'University', fundingAmount: '€1,400 / month + Full Tuition Coverage + Travel Allowance', degreeLevel: 'Master', deadline: 'January - March', eligibility: 'Global applicants holding relevant Bachelor degree applying to Erasmus Mundus programs with Austrian university partners.', officialWebsite: 'https://ec.europa.eu/programmes/erasmus-plus/', description: 'EU mobility scholarship for multi-university Master programs including Austrian institutions. Full funding including tuition fee waiver.' },
      { id: 'at-s-4', countryId: 'c-at', title: 'University of Vienna Excellence Scholarship', providerType: 'University', fundingAmount: '€750 / month (merit top-up)', degreeLevel: 'Master', deadline: 'Varies by Faculty (usually March–May)', eligibility: 'Enrolled international Master students with exceptional academic performance (GPA 1.5 or better on Austrian scale).', officialWebsite: 'https://www.univie.ac.at/en/studies/studying-in-vienna/scholarships/', description: 'Merit-based partial scholarship awarded by the University of Vienna to top-performing international students. Awarded after first semester enrollment.' },
      { id: 'at-s-5', countryId: 'c-at', title: 'TU Wien International Excellence Scholarship', providerType: 'University', fundingAmount: '€3,000 - €6,000 / year (tuition offset)', degreeLevel: 'Master', deadline: 'With admission application', eligibility: 'High-achieving international students admitted to TU Wien Master programs. Selection based on academic record and entrance exam performance.', officialWebsite: 'https://www.tuwien.at/en/studies/tuwien4u/scholarships/', description: 'Competitive tuition offset scholarship for non-EU/EEA students admitted to TU Wien. Effectively reduces or covers the €1,453.44/year tuition fee.' },
    ],
    livingCosts: [
      { id: 'at-lc-1', cityName: 'Vienna', rent: 560, food: 250, transport: 30, utilities: 100, internet: 25, entertainment: 110, monthlyTotal: 1075, description: 'Austria\'s capital is the most expensive city but also the most connected, with the cheapest public transport in Western Europe. The Wiener Linien annual student pass is ~€365/year (~€30/month). Strong international community.' },
      { id: 'at-lc-2', cityName: 'Graz', rent: 400, food: 210, transport: 40, utilities: 85, internet: 22, entertainment: 80, monthlyTotal: 837, description: 'Austria\'s most affordable major university city. Lively student scene, excellent quality of life, strong tech industry (AVL, Magna). Very walkable and cycle-friendly.' },
      { id: 'at-lc-3', cityName: 'Innsbruck', rent: 450, food: 220, transport: 35, utilities: 90, internet: 22, entertainment: 85, monthlyTotal: 902, description: 'Compact alpine city with world-class ski resorts within 20 minutes. Higher rent than Graz due to geography constraints, but exceptional lifestyle and safety.' },
      { id: 'at-lc-4', cityName: 'Salzburg', rent: 480, food: 230, transport: 35, utilities: 90, internet: 22, entertainment: 90, monthlyTotal: 947, description: 'UNESCO World Heritage city — birthplace of Mozart. Tourism-oriented economy provides part-time job opportunities in hospitality. Moderate student population compared to Vienna/Graz.' },
    ],
    accommodations: [
      { id: 'at-acc-1', type: 'Studentenheim (Student Dorm)', avgCostRange: '€250 – €500 / month (Utilities often included)', depositRequired: '1–2 months rent (€250–€600)', bookingPortals: 'OeAD Housing (housing.oead.at), ÖH portal, university housing office', tips: 'Apply for student dorm as soon as you receive your admission letter — waiting lists in Vienna can be 3–6 months. OeAD Housing guarantees rooms for international scholarship holders.', pros: 'Most affordable option, furnished, fast internet included, easy social integration with other international students.', cons: 'Long waiting lists in Vienna; smaller rooms compared to WG options.' },
      { id: 'at-acc-2', type: 'WG (Wohngemeinschaft — Shared Flat)', avgCostRange: '€300 – €600 / month', depositRequired: '2–3 months warm rent', bookingPortals: 'WG-Zimmer.at, willhaben.at, Facebook Groups (Wien WG Zimmer)', tips: 'Write personalized messages in German or English describing your lifestyle and habits. Be responsive — rooms go fast in Vienna. Check WG-Zimmer.at daily in June–August for winter semester rooms.', pros: 'Most popular choice, immediate availability, good social life, central locations available.', cons: 'Rental contracts are typically signed in German; review carefully or have someone translate.' },
      { id: 'at-acc-3', type: 'Private Apartment (Einzelwohnung)', avgCostRange: '€600 – €1,200 / month', depositRequired: '3 months cold rent', bookingPortals: 'willhaben.at, immobilien.net, HousingAnywhere', tips: 'Landlord must provide Mietvertrag (rental contract). Ensure you receive a Meldezettelbestätigung for address registration (Meldeamt). Apartments in Vienna\'s Ringstraße district command premium prices.', pros: 'Complete privacy, quiet environment for focused study.', cons: 'Most expensive option; often unfurnished in Austria (no kitchen appliances); SCHUFA/Bonitätsauskunft credit check required.' },
    ],
    partTimeJobs: [
      { id: 'at-pt-1', allowedHours: '20 hours / week during semester (employer must apply for AMS Beschäftigungsbewilligung)', minWage: 'No statutory national minimum — Kollektivverträge set rates (~€10–€14/hr for student jobs)', miniJobCap: '€518.44 / month (Geringfügigkeitsgrenze 2026 — below this: no social security contributions except accident insurance)', taxRules: 'Earnings below €518.44/month are exempt from mandatory social security contributions (except accident insurance). Above this limit, both employer and employee contribute to social security. Income tax (Einkommensteuer) applies on annual earnings above €11,693.', popularJobsJson: JSON.stringify(['Research / Teaching Assistant (Tutor at University): €11–€15/hr', 'Retail / Supermarket (Billa, Spar, Hofer): €10–€13/hr', 'Waiter / Hospitality Staff (kollektivvertrag): €11–€14/hr', 'English Tutor / Private Teaching: €15–€25/hr', 'IT Support / Junior Developer: €14–€20/hr', 'Delivery / Logistics (DPD, GLS): €12–€14/hr']), semesterRules: 'Maximum 20 hours per week during active semester. Employer must obtain AMS Beschäftigungsbewilligung (work permit) before you can legally start. Processing takes 2–6 weeks.', holidayRules: 'Full-time work allowed during official semester breaks. No daily cap during Semesterferien.', jobPortalsJson: JSON.stringify(['AMS.at (Public Employment Service — official job board)', 'Jobsuche.at', 'willhaben.at Jobs', 'LinkedIn Austria', 'University Career Center & ÖH Job Board']) },
    ],
    insurances: [
      { id: 'at-ins-1', type: 'Public', providerName: 'ÖGK (Österreichische Gesundheitskasse) — Student Self-Insurance', monthlyCost: '€78.84 / month (2026 rate; was €73.48 in 2025)', requirements: 'Enrolled as regular student (ordentliche/r Studierende/r), annual income below €15,000, study within standard program duration + 4 semesters.', coverageDetails: 'Full public health insurance: access to contracted Kassenärzte (doctors), hospital care, prescription medications via e-card, preventive screenings.', pros: 'Significantly cheaper than German GKV (~€78 vs ~€128/month). Covers all risks. Accepted everywhere in Austria. Apply at local ÖGK service center.', cons: 'Income limit (€15,000/year) means higher-earning working students may lose eligibility. Student-specific plan ends after tolerance semesters expire.', recommendedFor: 'All non-EU degree students under 30 not covered by family or employer insurance.' },
      { id: 'at-ins-2', type: 'Private', providerName: 'Mawista Student / DR-WALTER', monthlyCost: '~€30–€65 / month', requirements: 'For language course students, exchange students (under 12 months), or students whose ÖGK self-insurance is not yet active.', coverageDetails: 'Emergency medical treatment, acute illness, repatriation. Covers Austria and Schengen Area.', pros: 'Very affordable for short stays. Can be purchased quickly online. No income limit.', cons: 'Does NOT satisfy the residence permit all-risks requirement for a full degree study period. Not a substitute for ÖGK for multi-year students.', recommendedFor: 'Short-term students (language courses, exchange semesters under 6 months) or bridging coverage until ÖGK registration is complete.' },
      { id: 'at-ins-3', type: 'Private', providerName: 'ÖAMTC Insurance / Uniqa Student', monthlyCost: '~€60–€90 / month', requirements: 'Open to all international students regardless of income or study duration.', coverageDetails: 'Comprehensive all-risks coverage including routine doctor visits, specialist referrals, emergency care, and dental basics.', pros: 'No income cap, available for longer study durations, some plans include liability insurance.', cons: 'More expensive than ÖGK. Reimbursement-based (pay upfront, claim back). Some providers require German language documents.', recommendedFor: 'Students who exceed the ÖGK income threshold due to substantial part-time work, or those seeking a private insurance alternative.' },
    ],
    officialResources: [
      { id: 'at-r-1', title: 'OeAD – Austria\'s Agency for Education and Internationalisation', category: 'University', url: 'https://oead.at/en/', description: 'Official Austrian government agency for international students — scholarships, housing (housing.oead.at), and study information.', badgeText: 'Official Portal' },
      { id: 'at-r-2', title: 'Study in Austria (studyinaustria.at)', category: 'University', url: 'https://www.studyinaustria.at/', description: 'Official guide to studying in Austria — program search, university directory, scholarship database.', badgeText: 'Official Guide' },
      { id: 'at-r-3', title: 'Migration.gv.at — Austrian Immigration Portal', category: 'Visa', url: 'https://www.migration.gv.at/en/', description: 'Official Austrian immigration authority portal for residence permit and visa requirements. Use to verify current financial thresholds and documentation.', badgeText: 'Official Immigration' },
      { id: 'at-r-4', title: 'Austrian Embassy New Delhi', category: 'Visa', url: 'https://www.bmeia.gv.at/en/austrian-embassy-new-delhi/', description: 'Official Visa D and residence permit application center for Indian students. Book appointments and verify current document checklists here.', badgeText: 'Official Embassy' },
      { id: 'at-r-5', title: 'ÖGK – Österreichische Gesundheitskasse', category: 'General', url: 'https://www.gesundheitskasse.at/', description: 'Austria\'s national health insurance provider. Register for student self-insurance (Selbstversicherung für Studierende) at €78.84/month (2026).', badgeText: 'Health Insurance' },
      { id: 'at-r-6', title: 'AMS Austria – Labour Market Service', category: 'General', url: 'https://www.ams.at/en/', description: 'Austria\'s public employment service — employer applies here for student work permits (Beschäftigungsbewilligung). Job board for part-time student positions.', badgeText: 'Work Permits' },
      { id: 'at-r-7', title: 'OeAD Housing (housing.oead.at)', category: 'Housing', url: 'https://housing.oead.at/', description: 'Official student housing database managed by OeAD. Guarantees rooms for OeAD scholarship holders. Best starting point for finding student accommodation.', badgeText: 'Student Housing' },
    ],
    faqs: [
      { id: 'at-faq-1', question: 'How much is tuition at Austrian public universities for non-EU students?', answer: 'Non-EU/EEA students pay €726.72 per semester (€1,453.44 per year) in tuition at public Austrian universities. Additionally, all students pay the ÖH student union fee of ~€25.20/semester. EU/EEA students pay only the ÖH fee during standard program duration + 2 tolerance semesters.', category: 'Admission', tags: 'tuition, fees, non-EU, public university' },
      { id: 'at-faq-2', question: 'Do I need a blocked account (Sperrkonto) for Austria like Germany?', answer: 'No — unlike Germany, Austria does NOT mandate a blocked account. The required financial proof can be a personal bank statement showing sufficient funds, a scholarship letter, or a Haftungserklärung (guarantor declaration) from an Austrian resident. A blocked account is accepted but optional.', category: 'Visa', tags: 'blocked account, sperrkonto, financial proof' },
      { id: 'at-faq-3', question: 'How much financial proof is required for an Austrian student residence permit?', answer: 'The amount depends on your age: Under 24 years: €722.58/month (€8,670.96 for 12 months). 24 years or older: €1,308.39/month (€15,700.68 for 12 months). If your monthly rent exceeds €386.43, you must prove additional funds to cover the difference. Source: migration.gv.at (official 2026 figures).', category: 'Visa', tags: 'financial proof, residence permit, monthly amount' },
      { id: 'at-faq-4', question: 'Is an APS Certificate required for Austrian universities?', answer: 'No — APS (Akademische Prüfstelle) is a Germany-specific requirement for Indian students only. Austria does not use APS and Austrian universities evaluate your academic credentials directly without this intermediary verification.', category: 'Admission', tags: 'APS, certificate, india, not required' },
      { id: 'at-faq-5', question: 'Can I work part-time while studying in Austria?', answer: 'Yes, international (non-EU) students can work up to 20 hours per week during the semester and full-time during semester breaks. IMPORTANT: You cannot start working on your own — your employer must apply for a work permit (Beschäftigungsbewilligung) at the AMS (Arbeitsmarktservice) on your behalf. Processing takes 2–6 weeks.', category: 'Jobs', tags: 'part-time, work, 20 hours, AMS, permit' },
      { id: 'at-faq-6', question: 'What health insurance do I need as an international student in Austria?', answer: 'You need all-risks health insurance covering your entire stay. The most affordable option is the ÖGK (Österreichische Gesundheitskasse) student self-insurance at €78.84/month in 2026 — significantly cheaper than German statutory insurance (~€125-130/month). Apply at your local ÖGK service center with your Meldezettel and enrollment confirmation.', category: 'Insurance', tags: 'health insurance, ÖGK, monthly cost' },
      { id: 'at-faq-7', question: 'What is a Meldezettel and why is it important?', answer: 'A Meldezettel is the official address registration document required in Austria within 3 days of moving into any accommodation. You get it from the local Meldeamt (registration office). It is required for your ÖGK health insurance registration, residence permit application, opening a bank account, and virtually all official processes in Austria.', category: 'General', tags: 'meldezettel, registration, address, Meldeamt' },
      { id: 'at-faq-8', question: 'How do I apply to Austrian universities — is there a central portal like Uni-Assist?', answer: 'Austria does not have a centralized application portal equivalent to Germany\'s Uni-Assist. You apply directly through each university\'s own online admission portal. Most Austrian public universities have their own application system. Start applications 6–9 months before the semester begins. Typical deadlines: July 1–September 1 for Winter Semester (October start), November 1–February 1 for Summer Semester (March start).', category: 'Admission', tags: 'application portal, no uni-assist, direct application' },
      { id: 'at-faq-9', question: 'What happens after my student visa — do I need a residence permit?', answer: 'Yes. You enter Austria on a Visa D (National Visa). Once in Austria, you must apply for a Residence Permit for Students (Aufenthaltsbewilligung Studierende) at your local Magistrat or Bezirkshauptmannschaft within 3 months of arrival. The residence permit fee is €218 (as of January 2026). Processing takes 6 weeks to 6 months — apply early.', category: 'Visa', tags: 'residence permit, Aufenthaltsbewilligung, visa D' },
      { id: 'at-faq-10', question: 'Does Austria have a minimum wage?', answer: 'Austria does not have a statutory national minimum wage like Germany\'s €13.90/hour. Instead, wages are set by industry-specific collective bargaining agreements (Kollektivverträge). The average minimum set by these agreements is approximately €1,700 gross/month for full-time work. For student part-time jobs, typical rates range from €10–€15/hour depending on the sector.', category: 'Jobs', tags: 'minimum wage, kollektivvertrag, no statutory minimum' },
    ],
  };
}
